name = "master-router"
main = "src/index.js"
compatibility_date = "2024-11-18"

# Masukkan semua domain kamu di sini (Wildcard)
# Ini menggantikan setting manual di Dashboard Triggers
routes = [
		{ pattern = "*.bokklastread.co.uk/*", zone_name = "bokklastread.co.uk" }
		
]















